/* Generated by tools/build.mjs from content.json — do not edit by hand.
   Change content.json and run: npm run build */
window.KLContent = {
  "site": {
    "artistName": "khxngLX",
    "givenName": "khang LE",
    "tagline": "artist, producer, engineer",
    "description": "khxngLX — Khang Le. Musician and producer. Hip hop, indie, experimental. Moody, atmospheric, introspective.",
    "email": "khang.le@ufl.edu",
    "phone": "+1 352 494 4349",
    "footerNote": "made with intention"
  },
  "links": [
    {
      "label": "@dr.khxng",
      "url": "https://www.instagram.com/dr.khxng/"
    }
  ],
  "intro": {
    "from": "khangLE",
    "to": "khxngLX"
  },
  "hero": {
    "portrait": "haz1026",
    "eyebrow": "artist · producer · engineer",
    "lineOne": {
      "from": "khang",
      "to": "khxng"
    },
    "lineTwo": {
      "from": "LE",
      "to": "LX"
    },
    "statement": "Moody, atmospheric, introspective. Vietnamese roots. Every sound has a purpose."
  },
  "marquee": [
    "hip hop",
    "indie",
    "experimental"
  ],
  "social": {
    "title": "elsewhere",
    "items": [
      {
        "platform": "instagram",
        "handle": "@dr.khxng",
        "url": "https://www.instagram.com/dr.khxng/"
      },
      {
        "platform": "spotify",
        "handle": "",
        "url": ""
      },
      {
        "platform": "soundcloud",
        "handle": "",
        "url": ""
      },
      {
        "platform": "youtube",
        "handle": "",
        "url": ""
      },
      {
        "platform": "apple music",
        "handle": "",
        "url": ""
      },
      {
        "platform": "bandcamp",
        "handle": "",
        "url": ""
      }
    ]
  },
  "projects": [
    {
      "slug": "untitled",
      "title": "untitled",
      "status": "coming soon",
      "year": "2026",
      "role": "write · produce · mix",
      "img": "dsc9303",
      "note": "The one that started as a voice memo at 3am and refused to leave."
    },
    {
      "slug": "first-release",
      "title": "first release",
      "status": "in dev",
      "year": "2026",
      "role": "write · produce · engineer",
      "img": "haz1026",
      "note": "Everything before this was practice. This is the line in the sand."
    },
    {
      "slug": "love-and-sadness",
      "title": "love & sadness",
      "status": "upcoming",
      "year": "2026",
      "role": "write · vocals · produce",
      "img": "dsc9525",
      "note": "Two things that never showed up separately."
    },
    {
      "slug": "night-sessions",
      "title": "night sessions",
      "status": "in progress",
      "year": "2026",
      "role": "produce · engineer",
      "img": "dsc9662",
      "note": "Made entirely between midnight and the point where it stops being night."
    },
    {
      "slug": "working-together",
      "title": "working together",
      "status": "collab",
      "year": "2026",
      "role": "feature · production",
      "img": "dsc9664",
      "note": "Open door. Bring something honest."
    },
    {
      "slug": "whats-next",
      "title": "what's next",
      "status": "always",
      "year": "2026",
      "role": "write · produce",
      "img": "dsc9586",
      "note": "A placeholder that keeps refusing to stay one."
    },
    {
      "slug": "deep-cuts",
      "title": "deep cuts",
      "status": "recording",
      "year": "2026",
      "role": "write · vocals",
      "img": "dsc9717",
      "note": "The songs that did not fit anywhere, which is usually the tell."
    },
    {
      "slug": "soul-beats",
      "title": "soul beats",
      "status": "mixing",
      "year": "2026",
      "role": "produce · mix",
      "img": "dsc9679",
      "note": "Sample-led, warm, deliberately unhurried."
    },
    {
      "slug": "abstract-sounds",
      "title": "abstract sounds",
      "status": "experimental",
      "year": "2026",
      "role": "sound design",
      "img": "dsc9930",
      "note": "Texture first, song second. Sometimes song never."
    },
    {
      "slug": "new-era",
      "title": "new era",
      "status": "upcoming",
      "year": "2027",
      "role": "write · produce · engineer",
      "img": "dsc9601",
      "note": "Naming it early so there is something to live up to."
    }
  ],
  "stills": [
    {
      "img": "dsc9303",
      "cap": "blue hour"
    },
    {
      "img": "dsc9592",
      "cap": "long exposure"
    },
    {
      "img": "dsc9601",
      "cap": "last light"
    },
    {
      "img": "dsc9586",
      "cap": "running"
    },
    {
      "img": "dsc9525",
      "cap": "in the surf"
    },
    {
      "img": "dsc9664",
      "cap": "city behind"
    },
    {
      "img": "dsc9662",
      "cap": "the parapet"
    },
    {
      "img": "dsc9671",
      "cap": "folded"
    },
    {
      "img": "dsc9679",
      "cap": "red tile"
    },
    {
      "img": "dsc9695",
      "cap": "one light"
    },
    {
      "img": "dsc9717",
      "cap": "close"
    },
    {
      "img": "dsc9721",
      "cap": "hands"
    },
    {
      "img": "dsc9930",
      "cap": "blur"
    },
    {
      "img": "dsc9971",
      "cap": "streetlight"
    },
    {
      "img": "dsc9972",
      "cap": "the grass"
    },
    {
      "img": "dsc9973",
      "cap": "field"
    },
    {
      "img": "dsc9975",
      "cap": "the corner"
    },
    {
      "img": "dsc9976",
      "cap": "against the wall"
    },
    {
      "img": "haz1026",
      "cap": "back to the water"
    }
  ],
  "about": {
    "headshot": "dsc9717",
    "title": "i'm khang",
    "handleLine": "releasing as",
    "paragraphs": [
      "Musician and producer working in hip hop, indie and whatever sits between them.",
      "Vietnamese roots. Moody, atmospheric, introspective — I engineer, produce, write and rap, and I would rather a track be honest than clean.",
      "Authenticity over perfection. Every project starts with a feeling and the details turn into atmosphere.",
      "Open to collaborations with artists and producers who understand the vision."
    ],
    "highlights": [
      {
        "label": "artist & songwriter",
        "note": "vulnerability & emotion"
      },
      {
        "label": "producer & engineer",
        "note": "moody beats & atmosphere"
      },
      {
        "label": "rapper & vocalist",
        "note": "stories through song"
      },
      {
        "label": "indie first",
        "note": "vision over commercial"
      }
    ]
  },
  "merch": {
    "season": "gã ep.",
    "note": "first drop — coming soon",
    "shop": {
      "open": false,
      "currency": "$",
      "checkoutUrl": "",
      "closedNote": "The shop isn't open yet. Add your email below and I'll tell you when it is."
    },
    "categories": [
      "all",
      "cd",
      "vinyl",
      "poster",
      "shirts",
      "bag"
    ],
    "featured": [
      {
        "id": "ga-ep-vinyl",
        "name": "gã ep. — vinyl",
        "category": "vinyl",
        "meta": "12\" · limited",
        "price": null,
        "available": false,
        "status": "coming soon"
      },
      {
        "id": "ga-ep-cd",
        "name": "gã ep. — cd",
        "category": "cd",
        "meta": "digipak",
        "price": null,
        "available": false,
        "status": "coming soon"
      },
      {
        "id": "ga-ep-poster",
        "name": "gã ep. — poster",
        "category": "poster",
        "meta": "18 × 24",
        "price": null,
        "available": false,
        "status": "coming soon"
      },
      {
        "id": "ga-ep-tee",
        "name": "gã ep. — tee",
        "category": "shirts",
        "meta": "heavyweight cotton",
        "price": null,
        "available": false,
        "status": "coming soon"
      }
    ]
  },
  "resume": {
    "label": "resume",
    "expandable": true,
    "sections": [
      {
        "title": "releases",
        "from": "projects"
      },
      {
        "title": "roles",
        "entries": [
          {
            "title": "artist & songwriter",
            "subtitle": "writing, topline, vocals",
            "detail": "hip hop, indie, experimental"
          },
          {
            "title": "producer",
            "subtitle": "beats, arrangement, sound design",
            "detail": "sample-led, atmospheric"
          },
          {
            "title": "engineer",
            "subtitle": "recording, editing, mixing",
            "detail": "self-engineered throughout"
          }
        ]
      },
      {
        "title": "education",
        "entries": [
          {
            "period": "TODO years",
            "title": "University of Florida",
            "subtitle": "TODO degree",
            "detail": "TODO major or focus"
          }
        ]
      },
      {
        "title": "live",
        "text": "Delete this section until there's something in it.",
        "entries": [
          {
            "period": "TODO year",
            "title": "TODO venue or event",
            "subtitle": "TODO city",
            "detail": ""
          }
        ]
      }
    ]
  }
};
